FROM python:3.10-slim

WORKDIR /app

# Install necessary dependencies and clean up to save memory
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    build-essential \
    cmake \
    libboost-all-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



# Install Python dependencies
RUN pip install --no-cache-dir numpy paho-mqtt joblib pandas scipy matplotlib scikit-learn RPi.GPIO smbus2

# Copy the application code
COPY . /app/

# give full permissions to the /dev directory
RUN chmod -R 777 /dev

# Run the application
CMD ["python", "-m", "leg.models.realtime_inference"]
